"""KIS domain constants for domain-constant reuse."""

KIS_INDEX_KOSPI = "0001"
KIS_INDEX_KOSDAQ = "1001"
KIS_INDEX_KRX = "2001"

KIS_INDEX_LABELS = {
    KIS_INDEX_KOSPI: "KOSPI",
    KIS_INDEX_KOSDAQ: "KOSDAQ",
    KIS_INDEX_KRX: "KRX",
}

DEFAULT_KIS_INDEX_CODES = (KIS_INDEX_KOSPI, KIS_INDEX_KOSDAQ, KIS_INDEX_KRX)
